# Site settings
theme: jekyll-theme-cayman
title: Hello, World!
description: Hello world test only
# NOTE: this should be the project name if using GitHub Pages
baseurl: "/image-process-test"

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
