/*====================================================================*
 -  Copyright (C) 2001 Leptonica.  All rights reserved.
 -
 -  Redistribution and use in source and binary forms, with or without
 -  modification, are permitted provided that the following conditions
 -  are met:
 -  1. Redistributions of source code must retain the above copyright
 -     notice, this list of conditions and the following disclaimer.
 -  2. Redistributions in binary form must reproduce the above
 -     copyright notice, this list of conditions and the following
 -     disclaimer in the documentation and/or other materials
 -     provided with the distribution.
 -
 -  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 -  ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 -  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 -  A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL ANY
 -  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 -  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 -  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 -  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 -  OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 -  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 -  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *====================================================================*/

/*
 * fmorphautogen.c
 *
 *    This program is used to generate the two files.
 *    If filename is not given, the files are:
 *         fmorphgen.<n>.c
 *         fmorphgenlow.<n>.c
 *    where <n> is the input index.  Otherwise they are:
 *         <filename>.<n>.c
 *         <filename>low.<n>.c
 *    These two files, when compiled, implement dwa operations for
 *    all sels generated by selaAddBasic().
 *
 *    The library files fmorphgen.1.c and fmorphgenlow.1.c
 *    were made using index = 1.
 */

#include <allheaders.h>

#include <stdio.h>
#include <string.h>

void usage() {
	printf("Usage: dwagen <type> <index> <inputfile> <outputfile>\n"
		"  type: 'morph' or 'hmt'\n"
		"  index: an integer\n"
		"  inputfile: a text file containing SELs\n"
		"  outputfile: the name of output file\n\n"
		"Each SEL in the input file is formatted as follows:\n"
		"  * Any number of comment lines starting with '#' are ignored\n"
		"  * The next line contains the selname\n"
		"  * The next lines contain the Sel data with each line beginning and\n"
		"    ending with a double-quote, and showing the 2D layout.\n"
		"     (1) The text is an array of chars (in row-major order) where\n"
		"         each char can be one of the following:\n"
		"            'x': hit\n"
		"            'o': miss\n"
		"            ' ': don't-care\n"
		"     (2) When the origin falls on a hit or miss, use an upper case\n"
		"         char (e.g., 'X' or 'O') to indicate it.  When the origin\n"
		"         falls on a don't-care, indicate this with a 'C'.\n"
		"  * Each Sel ends when a blank line, a comment line, or the end of file\n\n"
		"The program will generate two files:\n"
		"  <outputfile>.<index>.c\n"
		"  <outputfile>low.<index>.c\n");
	exit(1);
}

int main(int    argc,
         char **argv)
{
	int type;
	char        *inputfile, *filename;
	l_int32      index;
	SELA        *sela;

	if (argc != 5) usage();

	if (strcmp(argv[1], "morph") == 0) type = 0;
	else if (strcmp(argv[1], "hmt") == 0) type = 1;
	else usage();

	index = atoi(argv[2]);
	inputfile = argv[3];
    filename = argv[4];

	sela = selaCreateFromFile(inputfile);
	if (sela == NULL) {
		printf("Error: failed to load input file '%s'\n", inputfile);
		return 1;
	}

	int ret = 0;

	if (type == 0) {
		ret = fmorphautogen(sela, index, filename);
	} else {
		ret = fhmtautogen(sela, index, filename);
	}

    selaDestroy(&sela);

	if (ret) {
		printf("Error: failed to generate output file '%s'\n", filename);
	}

	return ret;
}

